In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [3]:
# Membaca dataset dari file CSV menggunakan pandas
dataset = pd.read_csv('Churn_Modelling.csv')

# Memisahkan fitur-fitur yang digunakan untuk prediksi
# Menggunakan semua baris pada kolom ke-3 hingga kolom terakhir kecuali kolom terakhir
X = dataset.iloc[:, 3:-1].values

# Memisahkan variabel target atau label dari dataset
# Menggunakan semua baris pada kolom terakhir
y = dataset.iloc[:, -1].values


In [5]:
print(X) #cek data

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [6]:
# Mengimpor modul LabelEncoder dari pustaka sklearn.preprocessing
from sklearn.preprocessing import LabelEncoder

# Membuat objek LabelEncoder
le = LabelEncoder()

# Menggunakan LabelEncoder untuk melakukan transformasi pada kolom kedua dari array X
X[:, 2] = le.fit_transform(X[:, 2])


In [7]:
# Mengimpor modul ColumnTransformer dan OneHotEncoder dari pustaka scikit-learn
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

# Membuat objek ColumnTransformer dengan spesifikasi bahwa hanya kolom dengan indeks 1 yang akan diubah menggunakan OneHotEncoder, sementara kolom lainnya akan dilewati tanpa perubahan
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')

# Mengubah array X dengan menerapkan transformasi yang telah ditentukan sebelumnya
X = np.array(ct.fit_transform(X))


In [8]:
print(X) #cek data

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [9]:
# Mengimpor fungsi train_test_split dari pustaka sklearn.model_selection
from sklearn.model_selection import train_test_split

# Membagi data X dan y menjadi data pelatihan (X_train dan y_train) serta data pengujian (X_test dan y_test)
# dengan test_size = 0.2, yang berarti data pengujian akan memiliki ukuran 20% dari total data.
# random_state = 0 digunakan untuk mengontrol pembagian data secara acak sehingga memastikan hasil yang konsisten pada setiap eksekusi.
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)


In [10]:
# Mengimpor modul StandardScaler dari pustaka sklearn.preprocessing
from sklearn.preprocessing import StandardScaler

# Membuat objek scaler
sc = StandardScaler()

# Melakukan penskalaan fitur pada data pelatihan menggunakan metode fit_transform()
X_train = sc.fit_transform(X_train)

# Melakukan penskalaan fitur pada data pengujian menggunakan metode transform()
X_test = sc.transform(X_test)


Membuat model ANN

In [12]:
# Inisialisasi Model ANN
ann = tf.keras.models.Sequential()


In [13]:
#Membuat Input Layer dan Hidden Layer Pertama
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [14]:
#Membuat hidden layar kedua
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [15]:
#Membuat Output Layer
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

Training model



In [16]:
# Mengompilasi model
# 'adam' adalah optimizer yang digunakan untuk menyesuaikan berat model berdasarkan data pelatihan.
# 'binary_crossentropy' adalah fungsi kerugian yang cocok untuk masalah klasifikasi biner.
# 'accuracy' adalah metrik yang digunakan untuk memantau kinerja model selama pelatihan.
ann.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])


In [17]:
# Melatih model neural network dengan data pelatihan
# X_train merupakan data fitur, y_train merupakan target atau label yang sesuai
# batch_size = 32 menunjukkan bahwa model akan diperbarui setiap 32 sampel yang diteruskan
# epochs = 100 menunjukkan bahwa model akan melalui seluruh dataset pelatihan sebanyak 100 kali untuk pelatihan
ann.fit(X_train, y_train, batch_size=32, epochs=100)


Epoch 1/100
250/250 [==============================] - 4s 5ms/step - loss: 0.6675 - accuracy: 0.6148
Epoch 2/100
250/250 [==============================] - 1s 4ms/step - loss: 0.4974 - accuracy: 0.7936
Epoch 3/100
250/250 [==============================] - 1s 4ms/step - loss: 0.4570 - accuracy: 0.7971
Epoch 4/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4327 - accuracy: 0.8070
Epoch 5/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4117 - accuracy: 0.8234
Epoch 6/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3923 - accuracy: 0.8320
Epoch 7/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3771 - accuracy: 0.8419
Epoch 8/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3678 - accuracy: 0.8457
Epoch 9/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3615 - accuracy: 0.8479
Epoch 10/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3574 - accura

Modelkan data baru dan buat prediksi

In [18]:
# Melakukan prediksi menggunakan model jaringan saraf tiruan (ann)
# ann.predict digunakan untuk melakukan prediksi berdasarkan data yang diberikan sebagai argumen
# sc.transform digunakan untuk mentransformasikan data sesuai dengan skala yang telah dipelajari oleh StandardScaler (sc) sebelumnya
# [[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]] adalah data yang akan diprediksi, harus berada dalam format array 2D
# > 0.5 digunakan untuk mengonversi output prediksi menjadi bentuk biner dengan menggunakan ambang batas 0.5. Jika nilai prediksi lebih besar dari 0.5, hasilnya akan True, sebaliknya False.
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)


1/1 [==============================] - 0s 237ms/step
[[False]]


Prediksi data testing

In [19]:
# Menggunakan model yang dilatih (ann) untuk membuat prediksi pada data uji (X_test).
y_pred = ann.predict(X_test)

# Mengonversi hasil prediksi menjadi kelas biner berdasarkan ambang batas 0.5.
y_pred = (y_pred > 0.5)

# Menggabungkan dua larik menjadi satu, menampilkan hasil prediksi (y_pred) dan data uji yang asli (y_test).
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))


63/63 [==============================] - 0s 4ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


cek akurasi dan confusion matrix

In [20]:
# Mengimpor modul yang diperlukan
from sklearn.metrics import confusion_matrix, accuracy_score

# Menghitung confusion matrix
cm = confusion_matrix(y_test, y_pred)

# Menampilkan confusion matrix
print(cm)

# Menghitung dan menampilkan nilai akurasi
accuracy_score(y_test, y_pred)


[[1528   67]
 [ 209  196]]


0.862