**Machine Learning - Praktikum 4**

Praktikum ini dilakukan menggunakan Google Colab.

**Instalasi Tensorflow**

In [2]:
# Requires the latest pip
!pip install --upgrade pip

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 10.2 MB/s eta 0:00:00
  Attempting uninstall: pip
    Found existing installation: pip 23.1.2
    Uninstalling pip-23.1.2:
      Successfully uninstalled pip-23.1.2


In [3]:
# Current stable release for CPU and GPU
!pip install tensorflow

**Pra Pengolahan Data**

Langkah 1 - Import Library

In [4]:
import numpy as np
import pandas as pd
import tensorflow as tf

Langkah 2 - Load Data

In [6]:
dataset = pd.read_csv('/content/Churn_Modelling.csv') # Membaca file CSV.
X = dataset.iloc[:, 3:-1].values # Menentukan fitur dari dataset.
y = dataset.iloc[:, -1].values # Menentukan label atau target dari dataset.

In [7]:
print(X) # Cek data.

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


Langkah 3 - Encoding Data Kategorikal

In [8]:
from sklearn.preprocessing import LabelEncoder # mengimpor LabelEncoder.
le = LabelEncoder() # Membuat objek LabelEncoder.
X[:, 2] = le.fit_transform(X[:, 2]) # Mengubah nilai-nilai pada kolom kedua.

In [9]:
print(X) # Cek data.

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


Langkah 4 - Encoding Kolom "Geography" dengan One Hot Encoder

In [10]:
from sklearn.compose import ColumnTransformer # mengimpor ColumnTransformer.
from sklearn.preprocessing import OneHotEncoder # Digunakan untuk melakukan one-hot encoding.
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough') # membuat objek yang akan mengubah data.
X = np.array(ct.fit_transform(X)) # Menerapkan transformasi yang sudah didefinisikan.

In [11]:
print(X) # Cek data.

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


Langkah 5 - Split Data

In [12]:
from sklearn.model_selection import train_test_split # Digunakan untuk membagi dataset menjadi dua subset.
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0) # Digunakan untuk melakukan pemisahan dataset menjadi set pelatihan dan set pengujian.

Langkah 6 - Scaling Fitur

In [13]:
from sklearn.preprocessing import StandardScaler # Digunakan untuk melakukan penskalaan fitur.
sc = StandardScaler() # Digunakan untuk melakukan penskalaan fitur.
X_train = sc.fit_transform(X_train) # Menerapkan penskalaan standar pada set pelatihan.
X_test = sc.transform(X_test) # Melakukan penskalaan pada set pengujian.

**Membuat Model ANN**

Langkah 1 - Inisiasi Model ANN

In [14]:
ann = tf.keras.models.Sequential()

Langkah 2 - Membuat Input Layer dan Hidden Layer Pertama

In [15]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

Langkah 3 - Membuat Hidden Layer Kedua

In [16]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

Langkah 4 - Membuat Output Layer

In [17]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

**Training Model**

Langkah 1 - Compile Model (Menyatukan Arsitektur) ANN

In [18]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

Langkah 2 - Fitting Model

In [19]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 2s 2ms/step - loss: 0.5623 - accuracy: 0.7940
Epoch 2/100
250/250 [==============================] - 1s 2ms/step - loss: 0.5043 - accuracy: 0.7960
Epoch 3/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4719 - accuracy: 0.7958
Epoch 4/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4360 - accuracy: 0.8081
Epoch 5/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4124 - accuracy: 0.8154
Epoch 6/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4002 - accuracy: 0.8189
Epoch 7/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3932 - accuracy: 0.8210
Epoch 8/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3883 - accuracy: 0.8230
Epoch 9/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3841 - accuracy: 0.8260
Epoch 10/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3797 - accura

**Modelkan Data Baru dan Buat Prediksi**

In [20]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

1/1 [==============================] - 0s 107ms/step
[[False]]


Hasilnya false.

**Prediksi Dengan Data Testing**

In [21]:
y_pred = ann.predict(X_test) # Melakukan prediksi terhadap data set pengujian.
y_pred = (y_pred > 0.5) # Mengubah hasil prediksi.
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1)) # Melakukan print hasil perbandingan antara prediksi dan label aktual.

63/63 [==============================] - 0s 1ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


**Cek Akurasi dan Confusion Matrix**

In [22]:
from sklearn.metrics import confusion_matrix, accuracy_score # Digunakan untuk menghitung matriks kebingungan dan akurasi model.
cm = confusion_matrix(y_test, y_pred) # Menghitung matriks kebingungan.
print(cm) # Mencetak matriks kebingungan.
accuracy_score(y_test, y_pred) # Membandingkan label aktual dengan hasil prediksi dan menghitung seberapa akurat model tersebut.

[[1519   76]
 [ 199  206]]


0.8625