* Lakukan klasifikasi pada data MNIST dengan menggunakan model ANN
* Anda diperbolehkan melakukan eksplorasi terhadap,
    * Metode pra pengolahan
    * Pemilihan fitur
    * Arsitektur ANN
    * Fungsi Aktiviasi
* ANN diimplementasikan dengan menggunakan tensorflow.
* DIKERJAKAN SECARA BERKELOMPOK
* JELASKAN HASIL YANG ANDA DAPATKAN,
    * AKURASI
    * CONFUSION MATRIX
    * KONFIGURASI MODEL --> MULAI DARI PRA PENGOLAHAN SAMPAI ARSITEKTUR ANN

In [1]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

In [2]:
# Load the MNIST dataset
mnist = keras.datasets.mnist # 28x28 images of hand-written digits 0-9
(train_images, train_labels), (test_images, test_labels) = mnist.load_data() # Split into training and test sets

# Preprocessing
train_images, test_images = train_images / 255.0, test_images / 255.0 # Scale the pixel values from 0 to 1

# Build the ANN model
model = keras.Sequential([
    layers.Flatten(input_shape=(28, 28)),  # Flatten the 28x28 input images
    layers.Dense(128, activation='relu'),  # Hidden layer with ReLU activation
    layers.Dropout(0.2),                  # Dropout layer to reduce overfitting
    layers.Dense(10, activation='softmax') # Output layer with 10 classes and softmax activation
])

# Compile the model
model.compile(optimizer='adam', # Optimizer
              loss='sparse_categorical_crossentropy', # Loss function
              metrics=['accuracy']) # Accuracy metric

# Train the model
model.fit(train_images, train_labels, epochs=5) # Train the model for 5 epochs

# Evaluate the model on the test data
test_loss, test_accuracy = model.evaluate(test_images, test_labels) # Evaluate the model on the test data using `evaluate`

print(f'Test accuracy: {test_accuracy}') # Print test accuracy

# Confusion Matrix
predictions = model.predict(test_images) # Make predictions on the test data
confusion_matrix = tf.math.confusion_matrix(test_labels, tf.argmax(predictions, axis=1)) # Create a confusion matrix on the test data
print('Confusion Matrix:') # Print the confusion matrix
print(confusion_matrix) # Print the confusion matrix

11490434/11490434 [==============================] - 0s 0us/step
Epoch 1/5
1875/1875 [==============================] - 19s 10ms/step - loss: 0.2986 - accuracy: 0.9111
Epoch 2/5
1875/1875 [==============================] - 15s 8ms/step - loss: 0.1412 - accuracy: 0.9576
Epoch 3/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.1053 - accuracy: 0.9686
Epoch 4/5
1875/1875 [==============================] - 9s 5ms/step - loss: 0.0857 - accuracy: 0.9741
Epoch 5/5
313/313 [==============================] - 1s 2ms/step - loss: 0.0743 - accuracy: 0.9766
Test accuracy: 0.9765999913215637
313/313 [==============================] - 1s 3ms/step
Confusion Matrix:
tf.Tensor(
[[ 968    0    1    2    0    2    2    2    2    1]
 [   0 1123    3    1    0    0    1    1    6    0]
 [   3    2 1003    7    3    0    1    6    7    0]
 [   0    0    1  990    0    7    0    6    5    1]
 [   1    0    4    1  965    0    3    1    3    4]
 [   2    0    0   14    0  865    3    1    6