# Tugas

**Import Library**

In [3]:
import tensorflow as tf
from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Flatten, Dense
from tensorflow.keras.utils import to_categorical

**Create MNIST dataset**

In [4]:
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

**Preprocessing Data**

In [5]:
# Misalnya, normalisasi nilai piksel ke rentang 0-1
train_images = train_images / 255.0
test_images = test_images / 255.0

**Label Encoding**

In [6]:
# Ubah label ke one-hot encoding
train_labels = to_categorical(train_labels, 10)
test_labels = to_categorical(test_labels, 10)

**Create ANN Model**

In [7]:
model = Sequential()
model.add(Flatten(input_shape=(28, 28)))  # Layer input
model.add(Dense(128, activation='relu'))  # Hidden layer dengan aktivasi ReLU
model.add(Dense(10, activation='softmax'))  # Layer output dengan aktivasi softmax

**Model Compilation**

In [8]:
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

**Model Training**

In [9]:
model.fit(train_images, train_labels, epochs=10, batch_size=64, validation_split=0.2)

Epoch 1/10
750/750 [==============================] - 9s 4ms/step - loss: 0.3316 - accuracy: 0.9071 - val_loss: 0.1749 - val_accuracy: 0.9513
Epoch 2/10
750/750 [==============================] - 3s 3ms/step - loss: 0.1489 - accuracy: 0.9565 - val_loss: 0.1333 - val_accuracy: 0.9628
Epoch 3/10
750/750 [==============================] - 3s 4ms/step - loss: 0.1030 - accuracy: 0.9698 - val_loss: 0.1111 - val_accuracy: 0.9668
Epoch 4/10
750/750 [==============================] - 3s 4ms/step - loss: 0.0790 - accuracy: 0.9769 - val_loss: 0.0971 - val_accuracy: 0.9718
Epoch 5/10
750/750 [==============================] - 3s 3ms/step - loss: 0.0617 - accuracy: 0.9820 - val_loss: 0.0937 - val_accuracy: 0.9716
Epoch 6/10
750/750 [==============================] - 3s 3ms/step - loss: 0.0505 - accuracy: 0.9850 - val_loss: 0.0896 - val_accuracy: 0.9732
Epoch 7/10
750/750 [==============================] - 3s 3ms/step - loss: 0.0407 - accuracy: 0.9884 - val_loss: 0.0904 - val_accuracy: 0.9723
Epoch 

**Evaluate The Model on Test Data**

In [10]:
test_loss, test_acc = model.evaluate(test_images, test_labels)
print(f'Akurasi pengujian: {test_acc}')

313/313 [==============================] - 1s 2ms/step - loss: 0.0752 - accuracy: 0.9773
Akurasi pengujian: 0.9772999882698059


**Predictions with Models**

In [11]:
predictions = model.predict(test_images)

313/313 [==============================] - 1s 2ms/step


**Retrieves a Single Class Label from One-Hot Encoding**

In [12]:
import numpy as np
from sklearn.metrics import confusion_matrix

In [13]:
test_labels_single = np.argmax(test_labels, axis=1)

**Create a Matrix**

In [15]:
confusion = confusion_matrix(test_labels_single, np.argmax(predictions, axis=1))
print('Matrix:')
print(confusion)

Matrix:
[[ 971    1    2    0    0    0    3    1    2    0]
 [   0 1122    4    0    0    1    2    0    6    0]
 [   6    2 1002    3    1    0    2    8    8    0]
 [   1    0    5  985    0    6    0    4    5    4]
 [   1    0    3    1  960    1    5    1    1    9]
 [   2    0    0    6    0  874    2    1    5    2]
 [   7    2    3    1    5    3  935    0    2    0]
 [   1    4   14    2    1    1    0  998    1    6]
 [   2    0    6    6    3    5    2    6  940    4]
 [   3    2    0    4    6    4    0    3    1  986]]
