## **Praktikum 4**
### **Klasifikasi dengan ANN**

In [7]:
!php install --upgrade

Could not open input file: install


In [8]:
#for CPU users
!pip install tensorflow

  Obtaining dependency information for tensorflow from https://files.pythonhosted.org/packages/80/6f/57d36f6507e432d7fc1956b2e9e8530c5c2d2bfcd8821bcbfae271cd6688/tensorflow-2.14.0-cp311-cp311-win_amd64.whl.metadata
  Obtaining dependency information for tensorflow-intel==2.14.0 from https://files.pythonhosted.org/packages/ad/6e/1bfe367855dd87467564f7bf9fa14f3b17889988e79598bc37bf18f5ffb6/tensorflow_intel-2.14.0-cp311-cp311-win_amd64.whl.metadata
  Obtaining dependency information for absl-py>=1.0.0 from https://files.pythonhosted.org/packages/01/e4/dc0a1dcc4e74e08d7abedab278c795eef54a224363bb18f5692f416d834f/absl_py-2.0.0-py3-none-any.whl.metadata
  Obtaining dependency information for flatbuffers>=23.5.26 from https://files.pythonhosted.org/packages/6f/12/d5c79ee252793ffe845d58a913197bfa02ae9a0b5c9bc3dc4b58d477b9e7/flatbuffers-23.5.26-py2.py3-none-any.whl.metadata
     ---------------------------------------- 0.0/57.5 kB ? eta -:--:--
     ---------------------------------------- 57.5

In [10]:
#for CPU users
%pip install tensorflow

Note: you may need to restart the kernel to use updated packages.


### **Pra Pengolahan Data**
Langkah 1 - Import Library

In [11]:
import numpy as np
import pandas as pd
import tensorflow as tf

Langkah 2 - Load Data

In [12]:
dataset = pd.read_csv('data/Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values #Memilih fitur dari dataset ari kolom indeks ke-3 hingga kolom sebelum kolom terakhir. 
y = dataset.iloc[:, -1].values #Memilih target atau label kelas dari dataset

Cek data (X)

In [14]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


Langkah 3 - Encoding Data Kategorikal

In [15]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])
#mengubah kolom kedua dari data X (indeks 2 dalam representasi Python yang dimulai dari 0) menjadi bentuk numerik. 

In [16]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


Langkah 4 - Encoding Kolom "Geography" dengan One Hot Encoder

In [17]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

Kode ini melakukan transformasi One-Hot Encoding pada kolom kedua dari data X untuk mengubah variabel kategorikal menjadi bentuk biner yang dapat digunakan oleh algoritma pembelajaran mesin. Hasil transformasi ini akan menggantikan kolom kedua dalam data.

In [18]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


Langkah 5 - Split Data

In [19]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

Kode ini membagi dataset menjadi dua subset: data latih (80% dari dataset) dan data uji (20% dari dataset), yang akan digunakan untuk melatih dan menguji model. Hal ini memungkinkan untuk melakukan evaluasi kinerja model pada data yang belum pernah dilihat sebelumnya.

Langkah 6 - Scaling Fitur

In [20]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

Kode ini melakukan penskalaan fitur menggunakan StandardScaler untuk memastikan bahwa setiap fitur memiliki distribusi dengan rata-rata 0 dan deviasi standar 1.

### **Membuat Model ANN**
Langkah 1 - Inisiasi Model ANN

In [21]:
ann = tf.keras.models.Sequential()
#Membuat objek jaringan saraf tiruan dengan menggunakan model Sequential. 

Langkah 2 - Membuat Input Layer dan Hidden Layer Pertama

In [22]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

Langkah 3 - Membuat Hidden Layer Kedua

In [23]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

Kode ini menambahkan lapisan Dense dengan 6 neuron menggunakan fungsi aktivasi ReLU ke dalam jaringan saraf tiruan. 

Langkah 4 - Membuat Output Layer

In [24]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

Kode ini menambahkan lapisan Dense terakhir dengan satu neuron dan menggunakan fungsi aktivasi sigmoid ke dalam jaringan saraf tiruan. Lapisan ini akan menghasilkan probabilitas kelas positif pada tugas klasifikasi biner.

### **Training Model**
Langkah 1 - Compile Model (Menyatukan Arsitektur) ANN

In [25]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

Kode ini menentukan bagaimana jaringan saraf tiruan akan melakukan proses pelatihan. Ini termasuk pemilihan optimizer, fungsi loss, dan metrik evaluasi yang akan digunakan untuk memantau kinerja model.

Langkah 2 - Fitting Model

In [26]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 2s 3ms/step - loss: 0.5427 - accuracy: 0.7611
Epoch 2/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4698 - accuracy: 0.7952
Epoch 3/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4459 - accuracy: 0.7964
Epoch 4/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4334 - accuracy: 0.7991
Epoch 5/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4243 - accuracy: 0.8091
Epoch 6/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4169 - accuracy: 0.8140
Epoch 7/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4108 - accuracy: 0.8171
Epoch 8/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4056 - accuracy: 0.8219
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4007 - accuracy: 0.8244
Epoch 10/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3954 - accura

Kode ini melakukan proses pelatihan pada jaringan saraf tiruan dengan menggunakan data latih. Proses ini akan berlangsung selama 100 epoha, di mana pada setiap epoha, data akan dibagi menjadi batch-batch kecil sebesar 32 sampel untuk memperbarui bobot jaringan

### **Membuat Prediksi**
Diberikan informasi sebagai berikut,
- Geography: France
- Credit Score: 600
- Gender: Male
- Age: 40 years old
- Tenure: 3 years
- Balance: $ 60000
- Number of Products: 2
- Does this customer have a credit card ? Yes
- Is this customer an Active Member: Yes
- Estimated Salary: $ 50000

Apakah customer tersebut perlu dipertahankan?

Modelkan Data Baru dan Buat Prediksi

In [27]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)
#Memuat satu data baru yang akan diprediksi

1/1 [==============================] - 0s 142ms/step
[[False]]


Hasil prediksi adalah True jika model memprediksi kemungkinan pelanggan akan meninggalkan bank lebih dari 50%, dan False jika sebaliknya.

Prediksi Dengan Data Testing

In [28]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

63/63 [==============================] - 0s 2ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


Kode ini melakukan prediksi pada data uji menggunakan model jaringan saraf tiruan, dan kemudian membandingkan hasil prediksi dengan label kelas sebenarnya. Hasilnya adalah array dua kolom, di mana kolom pertama adalah prediksi model dan kolom kedua adalah label kelas sebenarnya.

Cek Akurasi dan Confusion Matrix

Kode ini digunakan untuk mengevaluasi kinerja model jaringan saraf tiruan menggunakan matriks kebingungannya (confusion matrix) dan akurasi.

In [29]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred) #Menghitung matriks kebingungannya dengan membandingkan label kelas sebenarnya 
print(cm) #Mencetak matriks 
accuracy_score(y_test, y_pred) #Menghitung akurasi dari model

[[1520   75]
 [ 198  207]]


0.8635