### **Anggota Kelompok :**
- Avifah Dwi Cahyani    (2141720053)
- Sabna Devi Kumalasari (2141720009)

### **Tugas**
- Lakukan klasifikasi pada data MNIST dengan menggunakan model ANN
- Anda diperbolehkan melakuka eksplorasi terhadap,
  - Metode pra pengolahan
  - Pemilihan fitur
  - Arsitektur ANN
  - Fungsi Aktiviasi
- ANN diimplementasikan dengan menggunakan tensorflow.
- DIKERJAKAN SECARA BERKELOMPOK
- JELASKAN HASIL YANG ANDA DAPATKAN,
  - AKURASI
  - CONFUSION MATRIX
  - KONFIGURASI MODEL --> MULAI DARI PRA PENGOLAHAN SAMPAI ARSITEKTUR ANN

#### **JAWAB**

Import Library dan Persiapan Data

In [1]:
import tensorflow as tf
from keras import layers, models
from sklearn.datasets import fetch_openml
from sklearn.model_selection import train_test_split
import numpy as np
import matplotlib.pyplot as plt

# Unduh dataset MNIST dari scikit-learn
mnist = fetch_openml('mnist_784')

# Pisahkan data gambar dan label
images = mnist.data.astype('float32')
labels = mnist.target.astype('int')

c:\Users\t470s\anaconda3\Lib\site-packages\sklearn\datasets\_openml.py:1002: FutureWarning: The default value of `parser` will change from `'liac-arff'` to `'auto'` in 1.4. You can set `parser='auto'` to silence this warning. Therefore, an `ImportError` will be raised from 1.4 if the dataset is dense and pandas is not installed. Note that the pandas parser may return different data types. See the Notes Section in fetch_openml's API doc for details.
  warn(


Langkah 1
Pra-pemrosesan

In [2]:
images /= 255.0  # Skalakan data

# Bagi data menjadi data pelatihan dan pengujian
train_images, test_images, train_labels, test_labels = train_test_split(
    images, labels, test_size=0.2, random_state=42)

Langkah 2 Definisikan arsitektur model ANN

In [3]:
model = models.Sequential([
    layers.Reshape(target_shape=(28, 28, 1), input_shape=(784,)), #engubah bentuk input dari vektor 1D (784 elemen) menjadi matriks 3D (28x28x1). 
    layers.Conv2D(32, (3, 3), activation='relu', input_shape=(28, 28, 1)), #Menambahkan lapisan konvolusi dengan 32 filter, masing-masing berukuran 3x3, dan fungsi aktivasi ReLU.
    layers.MaxPooling2D((2, 2)), #Menambahkan lapisan max pooling dengan ukuran jendela 2x2.
    layers.Flatten(), #Mengubah output dari lapisan sebelumnya (berupa matriks) menjadi vektor 1D.
    layers.Dense(128, activation='relu'), #Menambahkan lapisan terhubung penuh (fully connected) dengan 128 neuron dan fungsi aktivasi ReLU.
    layers.Dense(64, activation='relu'), #Menambahkan lapisan terhubung penuh dengan 64 neuron dan fungsi aktivasi ReLU.
    layers.Dense(10, activation='softmax') #Menambahkan lapisan terhubung penuh dengan 10 neuron (sesuai dengan jumlah kelas digit) dan fungsi aktivasi softmax.
])

Kode ini mendefinisikan struktur model CNN untuk pengenalan digit tulisan tangan. Model ini memiliki lapisan konvolusi, max pooling, dan lapisan terhubung penuh untuk memproses data gambar MNIST. Fungsi aktivasi ReLU digunakan di sebagian besar lapisan, dan pada lapisan terakhir menggunakan softmax untuk mendapatkan probabilitas kelas.

Langkah 3 Kompilasi model

In [4]:
model.compile(optimizer='adam', #mengoptimalkan proses pelatihan
              loss='sparse_categorical_crossentropy', # Memilih fungsi kerugian untuk masalah klasifikasi dengan banyak kelas.
              metrics=['accuracy']) #Menggunakan metrik akurasi untuk memantau kinerja model selama proses pelatihan.

Langkah 4 Latih model

In [5]:
history = model.fit(train_images, train_labels,
                    epochs=10, validation_split=0.2)

Epoch 1/10
1400/1400 [==============================] - 50s 34ms/step - loss: 0.1825 - accuracy: 0.9440 - val_loss: 0.0734 - val_accuracy: 0.9764
Epoch 2/10
1400/1400 [==============================] - 47s 34ms/step - loss: 0.0585 - accuracy: 0.9817 - val_loss: 0.0533 - val_accuracy: 0.9830
Epoch 3/10
1400/1400 [==============================] - 37s 26ms/step - loss: 0.0373 - accuracy: 0.9887 - val_loss: 0.0558 - val_accuracy: 0.9823
Epoch 4/10
1400/1400 [==============================] - 39s 28ms/step - loss: 0.0255 - accuracy: 0.9923 - val_loss: 0.0695 - val_accuracy: 0.9782
Epoch 5/10
1400/1400 [==============================] - 36s 26ms/step - loss: 0.0188 - accuracy: 0.9937 - val_loss: 0.0575 - val_accuracy: 0.9816
Epoch 6/10
1400/1400 [==============================] - 38s 27ms/step - loss: 0.0137 - accuracy: 0.9957 - val_loss: 0.0581 - val_accuracy: 0.9852
Epoch 7/10
1400/1400 [==============================] - 43s 31ms/step - loss: 0.0107 - accuracy: 0.9965 - val_loss: 0.0604 -

Kode ini memulai proses pelatihan pada model jaringan saraf dengan menggunakan data latih dari dataset MNIST. Proses ini akan berlangsung selama 10 epoha, dan akan ada evaluasi pada data validasi setiap akhir epoha. Informasi tentang hasil pelatihan akan disimpan dalam variabel history.

Langkah 5: Evaluasi model pada data pengujian

In [6]:
test_loss, test_acc = model.evaluate(test_images, test_labels)
print(f'Akurasi pada data pengujian: {test_acc:.2f}')

438/438 [==============================] - 3s 7ms/step - loss: 0.0823 - accuracy: 0.9836
Akurasi pada data pengujian: 0.98


Kode ini mengukur kinerja model pada data uji setelah proses pelatihan selesai. Hasilnya adalah akurasi model pada data uji. Akurasi adalah rasio prediksi benar terhadap total predik

In [7]:
# Evaluasi akurasi data pelatihan
train_loss, train_acc = model.evaluate(train_images, train_labels)
print(f'Akurasi pada data pelatihan: {train_acc:.2f}')

1750/1750 [==============================] - 11s 6ms/step - loss: 0.0174 - accuracy: 0.9957
Akurasi pada data pelatihan: 1.00


Kode ini mengukur kinerja model pada data latih setelah proses pelatihan selesai. Hasilnya adalah akurasi model pada data latih. Akurasi adalah rasio prediksi benar terhadap total prediksi.

In [8]:
from sklearn.metrics import confusion_matrix

# Membuat prediksi pada data pengujian
predictions = model.predict(test_images)
predicted_labels = np.argmax(predictions, axis=1)

# Membuat matriks kebingungan
confusion = confusion_matrix(test_labels, predicted_labels)
print('Matriks Kebingungan:')
print(confusion)

438/438 [==============================] - 3s 7ms/step
Matriks Kebingungan:
[[1337    1    1    0    1    0    2    1    0    0]
 [   1 1586    2    0    4    0    5    1    1    0]
 [   1    5 1356    1    5    0    1    3    4    4]
 [   3    1   12 1397    0    4    0    4    4    8]
 [   1    0    0    0 1286    0    0    1    0    7]
 [   0    0    0    6    0 1251    8    0    3    5]
 [   5    0    0    0    2    3 1386    0    0    0]
 [   2    1   15    2    9    1    0 1462    1   10]
 [   3    3    2    5    4    4    6    3 1321    6]
 [   5    2    1    3   12    3    0    3    2 1389]]


Kode ini menghasilkan dan mencetak matriks kebingungan dari hasil prediksi model pada data uji. 