<a href="https://colab.research.google.com/github/MuizzuddinRifqi/Machine-Learning-Kelas-3E/blob/main/18%20M.%20Muizzuddin%20Rifqi/Pertemuan%2010%20-%20Recurrent%20Neural%20Network%20(RNN)/Tugas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tugas Praktikum

- Modifikasi model CNN pada praktikum 2 sehingga didapatkan akurasi testing lebih dari 80%.
- Buatlah model CNN untuk klasifikasi dataset MNIST.

**Klasifikasi dataset MNIST**

In [2]:
import tensorflow as tf

from tensorflow.keras import datasets, layers, models
from sklearn.model_selection import train_test_split
from sklearn.datasets import fetch_openml

## Pra-pengolahan data MNIST

In [3]:
# Pra-pengolahan data
mnist = fetch_openml('mnist_784')

# memisahkan data gambar dengan label
gambar = mnist.data.astype('float32')
label = mnist.target.astype('int')

# normalisasi rentang nilai piksel menjadi antara 1 dan 0
gambar /= 255.0  # Skalakan data

# Bagi data menjadi data pelatihan dan pengujian (split data)
train_images, test_images, train_labels, test_labels = train_test_split(
    gambar, label, test_size=0.2, random_state=42)


/usr/local/lib/python3.10/dist-packages/sklearn/datasets/_openml.py:968: FutureWarning: The default value of `parser` will change from `'liac-arff'` to `'auto'` in 1.4. You can set `parser='auto'` to silence this warning. Therefore, an `ImportError` will be raised from 1.4 if the dataset is dense and pandas is not installed. Note that the pandas parser may return different data types. See the Notes Section in fetch_openml's API doc for details.
  warn(


## Buat Model CNN

In [4]:
# buat model dan layer konvolusi.
# Layer Fully Connected (input) dan (output).
model = models.Sequential(
    [
        layers.Reshape(target_shape=(28, 28, 1), input_shape=(784,)),
        layers.Conv2D(32, (3, 3), activation='relu', input_shape=(28, 28, 1)),
        layers.MaxPooling2D((2, 2)),
        layers.Flatten(),
        layers.Dense(128, activation='relu'),
        layers.Dense(64, activation='relu'),
        layers.Dense(10, activation='softmax')
    ]
)

## Kompilasi Model dan Melakukan Training model

In [5]:
# Kompilasi model
#
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

# Latih model
history = model.fit(train_images, train_labels,
                    epochs=10, validation_split=0.2)


Epoch 1/10
1400/1400 [==============================] - 17s 5ms/step - loss: 0.1847 - accuracy: 0.9433 - val_loss: 0.0812 - val_accuracy: 0.9751
Epoch 2/10
1400/1400 [==============================] - 5s 4ms/step - loss: 0.0575 - accuracy: 0.9819 - val_loss: 0.0523 - val_accuracy: 0.9839
Epoch 3/10
1400/1400 [==============================] - 6s 4ms/step - loss: 0.0377 - accuracy: 0.9880 - val_loss: 0.0510 - val_accuracy: 0.9833
Epoch 4/10
1400/1400 [==============================] - 5s 4ms/step - loss: 0.0242 - accuracy: 0.9925 - val_loss: 0.0634 - val_accuracy: 0.9796
Epoch 5/10
1400/1400 [==============================] - 6s 4ms/step - loss: 0.0182 - accuracy: 0.9942 - val_loss: 0.0522 - val_accuracy: 0.9854
Epoch 6/10
1400/1400 [==============================] - 6s 4ms/step - loss: 0.0133 - accuracy: 0.9958 - val_loss: 0.0546 - val_accuracy: 0.9845
Epoch 7/10
1400/1400 [==============================] - 6s 4ms/step - loss: 0.0123 - accuracy: 0.9958 - val_loss: 0.0532 - val_accuracy

## Evaluasi Model

In [6]:
# evaluasi akurasi data testing
test_loss, test_acc = model.evaluate(test_images, test_labels)
print(f'Akurasi pada data testing: {test_acc:.2f}')

# evaluasi akurasi data training
train_loss, train_acc = model.evaluate(train_images, train_labels)
print(f'Akurasi pada data training: {train_acc:.2f}')


438/438 [==============================] - 1s 3ms/step - loss: 0.0897 - accuracy: 0.9827
Akurasi pada data testing: 0.98
1750/1750 [==============================] - 4s 2ms/step - loss: 0.0236 - accuracy: 0.9938
Akurasi pada data training: 0.99


## Confusion Matrix untuk Data Tesing

In [7]:
from sklearn.metrics import confusion_matrix
import numpy as np

# Membuat prediksi pada data testing
predictions = model.predict(test_images)
predicted_labels = np.argmax(predictions, axis=1)

# Membuat matriks kebingungan
confusion = confusion_matrix(test_labels, predicted_labels)
print('Confusion Matrix:')
print(confusion)

438/438 [==============================] - 1s 2ms/step
Confusion Matrix:
[[1338    1    1    0    0    0    1    1    1    0]
 [   0 1594    1    2    0    0    0    2    0    1]
 [   1    4 1369    0    0    1    0    3    2    0]
 [   2    2   16 1389    0   13    0    4    7    0]
 [   1    0    3    0 1271    0    1    6    5    8]
 [   1    0    1    2    0 1258    2    0    9    0]
 [   8    1    0    0    2    5 1379    0    1    0]
 [   3    4   13    0    2    0    0 1474    4    3]
 [   1    3    9    4    0    3    2    2 1332    1]
 [   6    2    0    4    8    4    0    9   33 1354]]
