# **Praktikum 4**

Klasifikasi dengan ANN

### **Deskripsi**


Pada praktikum kali ini, Anda diminta untuk membuat model ANN untuk mengklasifikasi potensi seorang customer akan meninggalkan perusahaan Anda atau tidak. Istirlah populer dari fenomena ini disebut sebagai 'churn'. Tingkat churn yang tinggi (chrun rate) akan berdampak tidak baik bagi perusahaan.

### ⚠ **Perhatian!** ⚠

Pada praktikum ini, Anda akan menggunakan library tensorflow dari google. Oleh karena itu, Anda diharuskan untuk menginstal tensorflow terlebih dahulu.
Anda juga perlu menyesuaikan instalasi tensorflow yang Anda gunakan pada komputer lokal, apakah komputasi pada,
* CPU
* GPU (GPU support CUDA)
* Apple Silicon (M1/M2)

Panduan instalasi,

* https://www.tensorflow.org/install
* https://developer.apple.com/metal/tensorflow-plugin/
* https://caffeinedev.medium.com/how-to-install-tensorflow-on-m1-mac-8e9b91d93706

# **Pra Pengolahan Data**

### **Langkah 1 - Import Library**

In [20]:
import numpy as np # Mengimpor pustaka NumPy ke dalam program yang dimana library ini berfungsi untuk komputasi numerik dalam pengolahan data dan array.
import pandas as pd # Mengimpor pustaka Pandas ke dalam program yang dimana library ini berfungsi untuk memanipulasi dan analisis data tabular.
import tensorflow as tf # mengimpor pustaka TensorFlow ke dalam program Python yang digunakan untuk mengembangkan dan melatih model pembelajaran mesin, terutama dalam konteks pembelajaran mendalam (deep learning) dan jaringan saraf (neural networks).

### **Langkah 2 - Load Data**

In [21]:
dataset = pd.read_csv('Churn_Modelling.csv') # Mengimpor dataset dari file CSV 'Churn_Modelling.csv' ke dalam dataframe menggunakan library pandas (pd).
X = dataset.iloc[:, 3:-1].values # Mengambil subset dari dataset, yaitu kolom 3 hingga kolom sebelum terakhir, dan mengonversinya menjadi array NumPy.
y = dataset.iloc[:, -1].values # Mengambil kolom terakhir dari dataset dan mengonversinya menjadi array NumPy.

Cek data (X)

In [22]:
print(X) # Untuk mencetak data (X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


### **Langkah 3 - Encoding Data Kategorikal**

In [23]:
hasil = ("Cek data (X) dengan print. Hasilnya,")
print (hasil)

from sklearn.preprocessing import LabelEncoder # Mengimpor pustaka LabelEncoder dari scikit-learn, yang digunakan untuk mengkodekan (mengubah) label kategori menjadi angka.
le = LabelEncoder() # Membuat objek LabelEncoder yang akan digunakan untuk melakukan transformasi label kategori.
X[:, 2] = le.fit_transform(X[:, 2]) # Mengambil kolom ke-2 dari matriks X (data fitur) dan mengubah label kategori dalam kolom tersebut menjadi angka menggunakan LabelEncoder yang telah dibuat sebelumnya.
print(X) # Untuk mencetak data (X)

Cek data (X) dengan print. Hasilnya,
[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


### **Langkah 4 - Encoding Kolom "Geography" dengan One Hot Encoder**

In [24]:
hasil = ("Cek data (X) dengan print. Hasilnya,")
print (hasil)

from sklearn.compose import ColumnTransformer # Mengimpor pustaka ColumnTransformer dari scikit-learn, yang digunakan untuk mengubah data dalam kolom tertentu.
from sklearn.preprocessing import OneHotEncoder # Mengimpor pustaka OneHotEncoder dari scikit-learn, yang digunakan untuk mengkodekan variabel kategoris menjadi vektor biner.
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough') # Membuat objek ColumnTransformer untuk mengubah kolom ke-1 dalam data menjadi representasi one-hot encoding dan menjaga kolom-kolom lainnya tidak berubah ("passthrough").
X = np.array(ct.fit_transform(X)) # Menggunakan ColumnTransformer untuk mengubah data X, sehingga kolom ke-1 telah di-encode menggunakan one-hot encoding, dan kolom lainnya tetap tidak berubah (passthrough). Data hasil transformasi disimpan kembali dalam X.

print (X) # Untuk mencetak data (X)

Cek data (X) dengan print. Hasilnya,
[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


### **Langkah 5 - Split Data**


In [25]:
# Mengimpor fungsi train_test_split dari pustaka scikit-learn. Fungsi ini digunakan untuk membagi data menjadi subset pelatihan dan pengujian.
from sklearn.model_selection import train_test_split

# Menggunakan fungsi train_test_split untuk membagi data menjadi data pelatihan (X_train, y_train) dan data pengujian (X_test, y_test). 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

### **Langkah 6 - Scaling Fitur**

In [26]:
from sklearn.preprocessing import StandardScaler # Mengimpor pustaka scikit-learn untuk penskalaan data.
sc = StandardScaler() # Membuat objek penskalaan data dengan metode StandarScaler. 

X_train = sc.fit_transform(X_train) # Menskala data pelatihan (X_train) sehingga memiliki rata-rata nol dan deviasi standar satu (standarisasi).
X_train = sc.fit_transform(X_train) # Menskala data pengujian (X_test) dengan parameter yang sama seperti yang digunakan pada data pelatihan. Hal ini memastikan data pengujian diperlakukan dengan cara yang sama seperti data pelatihan.
X_test = sc.transform(X_test) # Mentransformasi (normalisasi) data pengujian X_test menggunakan objek Scaler (sc) yang telah dipelajari dari data pelatihan.

# **Membuat Model ANN**

### **Langkah 1 - Inisiasi Model ANN**

In [27]:
ann = tf.keras.models.Sequential() # Membuat model jaringan saraf tiruan (ANN) menggunakan TensorFlow dengan arsitektur berurutan.

### **Langkah 2 - Membuat Input Layer dan Hidden Layer Pertama**

In [28]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu')) #  Menambahkan lapisan Dense (fully connected) dengan 6 unit neuron dan fungsi aktivasi ReLU ke dalam model ANN.

### **Langkah 3 - Membuat Hidden Layer Kedua**

In [29]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu')) # Menambahkan lapisan Dense kedua dengan 6 unit neuron dan fungsi aktivasi ReLU.

### **Langkah 4 - Membuat Output Layer**

In [30]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid')) # Menambahkan lapisan Dense terakhir dengan 1 unit neuron dan fungsi aktivasi sigmoid. Ini digunakan untuk output biner (0 atau 1).

# **Training Model**

### **Langkah 1 - Compile Model (Menyatukan Arsitektur) ANN**

In [31]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy']) # Mengompilasi model dengan pengaturan seperti pengoptimalan menggunakan 'adam', pengukuran kesalahan menggunakan 'binary_crossentropy' untuk masalah klasifikasi biner, dan pengukuran metrik akurasi.

### **Langkah 2 - Fitting Model**

In [32]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100) # Melatih model ANN dengan data pelatihan X_train dan label y_train. Ini dilakukan selama 100 iterasi (epochs) dengan ukuran batch sebesar 32. Tujuannya adalah untuk mengoptimalkan model untuk melakukan tugas klasifikasi yang sesuai dengan data pelatihan.

Epoch 1/100


250/250 [==============================] - 1s 2ms/step - loss: 0.5940 - accuracy: 0.7533
Epoch 2/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4830 - accuracy: 0.7960
Epoch 3/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4565 - accuracy: 0.7960
Epoch 4/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4416 - accuracy: 0.7965
Epoch 5/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4299 - accuracy: 0.8049
Epoch 6/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4192 - accuracy: 0.8154
Epoch 7/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4086 - accuracy: 0.8238
Epoch 8/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3995 - accuracy: 0.8276
Epoch 9/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3909 - accuracy: 0.8300
Epoch 10/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3833 - accuracy: 0.8317
E

# **Membuat Prediksi**

Diberikan informasi sebagai berikut,

* Geography: France
* Credit Score: 600
* Gender: Male
* Age: 40 years old
* Tenure: 3 years
* Balance: $ 60000
* Number of Products: 2
* Does this customer have a credit card ? Yes
* Is this customer an Active Member: Yes
* Estimated Salary: $ 50000

Apakah customer tersebut perlu dipertahankan?

### **Modelkan Data Baru dan Buat Prediksi**

In [33]:
# menghasilkan prediksi dari model jaringan saraf tiruan (neural network) untuk data masukan yang telah diubah skala, dan kemudian memeriksa apakah hasil prediksi lebih besar dari 0.5.
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

1/1 [==============================] - 0s 106ms/step
[[False]]


Apakah hasilnya **False**?

### **Prediksi Dengan Data Testing**

In [34]:
y_pred = ann.predict(X_test) # Menghasilkan prediksi model untuk data uji.
y_pred = (y_pred > 0.5) # mengonversi prediksi model ke dalam bentuk boolean, yaitu True jika nilai prediksi lebih besar dari 0.5, dan False sebaliknya.
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1)) #  Ini mencetak prediksi model dan label sebenarnya untuk data uji dalam satu baris.

63/63 [==============================] - 0s 1ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


### **Cek Akurasi dan Confusion Matrix**

In [35]:
hasil = ("Hasil (bisa jadi berbeda),")
 
from sklearn.metrics import confusion_matrix, accuracy_score # Mengimpor modul untuk menghitung matriks kebingungan (confusion matrix) dan akurasi model.
cm = confusion_matrix(y_test, y_pred) # Menghitung matriks kebingungan berdasarkan prediksi model dan label sebenarnya dari data uji.
print(cm) # mencetak (print) matriks kebingungan (confusion matrix) ke layar. Matriks ini digunakan untuk mengevaluasi performa model klasifikasi dengan melihat sejauh mana model benar dan salah dalam mengklasifikasikan data.
accuracy_score(y_test, y_pred) # Menghitung akurasi model dengan membandingkan prediksi dengan label sebenarnya pada data uji.

[[1508   87]
 [ 195  210]]


0.859