# **PRAKTIKUM 4 - Klasifikasi dengan ANN**

### **Deskripsi**
Pada praktikum kali ini, Anda diminta untuk membuat model ANN untuk mengklasifikasi potensi seorang customer akan meninggalkan perusahaan Anda atau tidak. Istirlah populer dari fenomena ini disebut sebagai 'churn'. Tingkat churn yang tinggi (chrun rate) akan berdampak tidak baik bagi perusahaan.

**Install TensorFlow**

In [1]:
pip install --upgrade

Note: you may need to restart the kernel to use updated packages.


ERROR: You must give at least one requirement to install (see "pip help install")


In [2]:
# For CPU users
%pip install tensorflow

     ---------------------------------------- 0.0/57.5 kB ? eta -:--:--
     ----------------------------------- ---- 51.2/57.5 kB 1.3 MB/s eta 0:00:01
     ---------------------------------------- 57.5/57.5 kB 1.0 MB/s eta 0:00:00
     ---------------------------------------- 0.0/65.5 kB ? eta -:--:--
     ------------------ --------------------- 30.7/65.5 kB 1.3 MB/s eta 0:00:01
     ----------------------- -------------- 41.0/65.5 kB 487.6 kB/s eta 0:00:01
     -------------------------------------- 65.5/65.5 kB 502.2 kB/s eta 0:00:00
     ---------------------------------------- 0.0/1.5 MB ? eta -:--:--
     --------- ------------------------------ 0.4/1.5 MB 7.6 MB/s eta 0:00:01
     ------------------- -------------------- 0.7/1.5 MB 7.6 MB/s eta 0:00:01
     ---------------------------- ----------- 1.1/1.5 MB 7.6 MB/s eta 0:00:01
     ------------------------------------- -- 1.4/1.5 MB 8.1 MB/s eta 0:00:01
     ---------------------------------------  1.5/1.5 MB 7.3 MB/s eta 0:0

### **Pra Pengolahan Data**

### Langkah 1 - Import Library

In [3]:
import numpy as np
import pandas as pd
import tensorflow as tf

### Langkah 2 - Load Data

In [5]:
dataset = pd.read_csv('data/Churn_Modelling.csv') #digunakan untuk membaca file csv
X = dataset.iloc[:, 3:-1].values #Kode ini mengambil subset dari kolom-kolom di 'dataset'. iloc adalah metode yang digunakan untuk mengambil bagian dari DataFrame berdasarkan indeks.
y = dataset.iloc[:, -1].values #Kode ini mengambil kolom terakhir (indeks -1) dari 'dataset', yang umumnya berisi target atau label yang ingin diprediksi

#Jadi, kode tersebut membantu dalam memuat dataset, memisahkan fitur-fitur dari target, dan menyimpannya dalam variabel 'X' dan 'y' untuk analisis atau pemodelan lebih lanjut.

Cek data (X)

In [6]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


### Langkah 3 - Encoding Data Kategorikal

In [7]:
from sklearn.preprocessing import LabelEncoder #mengubah label kategori menjadi nilai numerik
le = LabelEncoder() #membuat objek LabelEncoder dengan nama 'le'. Objek ini akan digunakan untuk melakukan transformasi pada data kategori.
X[:, 2] = le.fit_transform(X[:, 2]) #Kode ini melakukan transformasi pada kolom kedua (indeks 2) dari matriks fitur 'X'.

Cek data (X) dengan print. Hasilnya,

In [8]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


### Langkah 4 - Encoding Kolom "Geography" dengan One Hot Encoder

In [9]:
from sklearn.compose import ColumnTransformer # untuk melakukan transformasi pada kolom-kolom tertentu dalam matriks fitur.
from sklearn.preprocessing import OneHotEncoder #digunakan untuk mengubah variabel kategori menjadi variabel dummy (variabel biner).
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough') #Kode ini membuat objek ColumnTransformer dengan nama 'ct'. Dalam kasus ini, kita hanya ingin melakukan transformasi pada kolom kedua (indeks 1) dari matriks fitur 'X
X = np.array(ct.fit_transform(X)) #Kode ini melakukan transformasi sebenarnya pada matriks fitur 'X' menggunakan objek ColumnTransformer 'ct'.

Cek data (X) dengan print.

In [10]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


### Langkah 5 - Split Data

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

### Langkah 6 - Scaling Fitur

In [12]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## **Membuat Model ANN**

### Langkah 1 - Inisiasi Model ANN

In [13]:
ann = tf.keras.models.Sequential()
#membuat sebuah model neural network menggunakan Sequential. Sequential adalah model yang memungkinkan Anda untuk membuat model secara berurutan, di mana Anda dapat menambahkan lapisan-lapisan ke model secara berurutan satu per satu.

### Langkah 2 - Membuat Input Layer dan Hidden Layer Pertama

In [14]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu')) #menambahkan lapisan Dense ke model ann.

### Langkah 3 - Membuat Hidden Layer Kedua

In [15]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Langkah 4 - Membuat Output Layer

In [16]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

## **Training Model**

### Langkah 1 - Compile Model (Menyatukan Arsitektur) ANN

In [17]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

### Langkah 2 - Fitting Model

In [18]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 3s 3ms/step - loss: 0.5858 - accuracy: 0.7479
Epoch 2/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4825 - accuracy: 0.7962
Epoch 3/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4447 - accuracy: 0.7975
Epoch 4/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4223 - accuracy: 0.8111
Epoch 5/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4040 - accuracy: 0.8281
Epoch 6/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3842 - accuracy: 0.8413
Epoch 7/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3711 - accuracy: 0.8493
Epoch 8/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3641 - accuracy: 0.8519
Epoch 9/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3599 - accuracy: 0.8536
Epoch 10/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3574 - accura

## **Membuat Prediksi**

Diberikan informasi sebagai berikut,
- Geography: France
- Credit Score: 600
- Gender: Male
- Age: 40 years old
- Tenure: 3 years
- Balance: $ 60000
- Number of Products: 2
- Does this customer have a credit card ? Yes
- Is this customer an Active Member: Yes
- Estimated Salary: $ 50000

Apakah customer tersebut perlu dipertahankan?

### **Modelkan Data Baru dan Buat Prediksi**

In [19]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

1/1 [==============================] - 0s 253ms/step
[[False]]


Apakah hasilnya False? Ya

### Prediksi Dengan Data Testing

In [20]:
y_pred = ann.predict(X_test) #digunakan untuk melakukan prediksi menggunakan model ann pada data pengujian (X_test).
y_pred = (y_pred > 0.5) #Kode ini mengubah hasil prediksi yang diperoleh dari model menjadi bentuk biner (True atau False) dengan menggunakan batas threshold 0.5.
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1)) 

63/63 [==============================] - 0s 3ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


### Cek Akurasi dan Confusion Matrix

In [21]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
#Kode ini menghitung matriks kebingungan dengan membandingkan hasil prediksi (y_pred) dengan data target sebenarnya (y_test). Hasilnya adalah matriks kebingungan yang berisi informasi tentang berapa banyak prediksi benar (True Positives dan True Negatives) dan berapa banyak prediksi salah (False Positives dan False Negatives).
print(cm)
accuracy_score(y_test, y_pred)

[[1513   82]
 [ 194  211]]


0.862