# **TUGAS**
- Avifah Dwi Cahyani (2141720053)
- Sabna Devi Kumalasari (2141720009)

- Lakukan klasifikasi pada data MNIST dengan menggunakan model ANN
- Anda diperbolehkan melakukan eksplorasi terhadap,
    - Metode pra pengolahan
    - Pemilihan fitur
    - Arsitektur ANN
    - Fungsi Aktiviasi
- ANN diimplementasikan dengan menggunakan **tensorflow**.
- DIKERJAKAN SECARA BERKELOMPOK
- JELASKAN HASIL YANG ANDA DAPATKAN,
    - AKURASI
    - CONFUSION MATRIX
    - KONFIGURASI MODEL --> MULAI DARI PRA PENGOLAHAN SAMPAI ARSITEKTUR ANN

---------------------
Import Library dan Persiapan Data

In [1]:
import tensorflow as tf
from keras import layers, models
from sklearn.datasets import fetch_openml
from sklearn.model_selection import train_test_split
import numpy as np
import matplotlib.pyplot as plt

# Unduh dataset MNIST dari scikit-learn
mnist = fetch_openml('mnist_784')

# Pisahkan data gambar dan label
images = mnist.data.astype('float32')
labels = mnist.target.astype('int')

c:\Users\WINDOWS 10\anaconda3\Lib\site-packages\sklearn\datasets\_openml.py:1002: FutureWarning: The default value of `parser` will change from `'liac-arff'` to `'auto'` in 1.4. You can set `parser='auto'` to silence this warning. Therefore, an `ImportError` will be raised from 1.4 if the dataset is dense and pandas is not installed. Note that the pandas parser may return different data types. See the Notes Section in fetch_openml's API doc for details.
  warn(


Langkah 1 pre-processing

In [2]:
images /= 255.0  # Skalakan data

# Bagi data menjadi data pelatihan dan pengujian
train_images, test_images, train_labels, test_labels = train_test_split(
    images, labels, test_size=0.2, random_state=42)

Langkah 2 Definisikan arsitektur model ANN

In [5]:
model = models.Sequential([
    layers.Reshape(target_shape=(28, 28, 1), input_shape=(784,)), #engubah bentuk input dari vektor 1D (784 elemen) menjadi matriks 3D (28x28x1). 
    layers.Conv2D(32, (3, 3), activation='relu', input_shape=(28, 28, 1)), #Menambahkan lapisan konvolusi dengan 32 filter, masing-masing berukuran 3x3, dan fungsi aktivasi ReLU.
    layers.MaxPooling2D((2, 2)), #Menambahkan lapisan max pooling dengan ukuran jendela 2x2.
    layers.Flatten(), #Mengubah output dari lapisan sebelumnya (berupa matriks) menjadi vektor 1D.
    layers.Dense(128, activation='relu'), #Menambahkan lapisan terhubung penuh (fully connected) dengan 128 neuron dan fungsi aktivasi ReLU.
    layers.Dense(64, activation='relu'), #Menambahkan lapisan terhubung penuh dengan 64 neuron dan fungsi aktivasi ReLU.
    layers.Dense(10, activation='softmax') #Menambahkan lapisan terhubung penuh dengan 10 neuron (sesuai dengan jumlah kelas digit) dan fungsi aktivasi softmax.
])

Kode ini mendefinisikan struktur model CNN untuk pengenalan digit tulisan tangan. Model ini memiliki lapisan konvolusi, max pooling, dan lapisan terhubung penuh untuk memproses data gambar MNIST. Fungsi aktivasi ReLU digunakan di sebagian besar lapisan, dan pada lapisan terakhir menggunakan softmax untuk mendapatkan probabilitas kelas.

Langkah 3 Kompilasi model

In [6]:
model.compile(optimizer='adam', #mengoptimalkan proses pelatihan
              loss='sparse_categorical_crossentropy', # Memilih fungsi kerugian untuk masalah klasifikasi dengan banyak kelas.
              metrics=['accuracy']) #Menggunakan metrik akurasi untuk memantau kinerja model selama proses pelatihan.

Langkah 4 Latih model

In [7]:
history = model.fit(train_images, train_labels,
                    epochs=10, validation_split=0.2)

Epoch 1/10
1400/1400 [==============================] - 29s 19ms/step - loss: 0.8351 - accuracy: 0.7280 - val_loss: 0.3914 - val_accuracy: 0.8877
Epoch 2/10
1400/1400 [==============================] - 25s 18ms/step - loss: 0.3484 - accuracy: 0.8958 - val_loss: 0.3027 - val_accuracy: 0.9094
Epoch 3/10
1400/1400 [==============================] - 25s 18ms/step - loss: 0.2704 - accuracy: 0.9180 - val_loss: 0.2443 - val_accuracy: 0.9255
Epoch 4/10
1400/1400 [==============================] - 26s 18ms/step - loss: 0.2156 - accuracy: 0.9348 - val_loss: 0.1991 - val_accuracy: 0.9383
Epoch 5/10
1400/1400 [==============================] - 26s 19ms/step - loss: 0.1785 - accuracy: 0.9458 - val_loss: 0.1778 - val_accuracy: 0.9462
Epoch 6/10
1400/1400 [==============================] - 26s 19ms/step - loss: 0.1560 - accuracy: 0.9522 - val_loss: 0.1551 - val_accuracy: 0.9529
Epoch 7/10
1400/1400 [==============================] - 26s 19ms/step - loss: 0.1390 - accuracy: 0.9574 - val_loss: 0.1468 -

Kode ini memulai proses pelatihan pada model jaringan saraf dengan menggunakan data latih dari dataset MNIST. Proses ini akan berlangsung selama 10 epoha, dan akan ada evaluasi pada data validasi setiap akhir epoha. Informasi tentang hasil pelatihan akan disimpan dalam variabel history.

Langkah 5: Evaluasi model pada data pengujian

In [8]:
test_loss, test_acc = model.evaluate(test_images, test_labels)
print(f'Akurasi pada data pengujian: {test_acc:.2f}')

438/438 [==============================] - 3s 6ms/step - loss: 0.1341 - accuracy: 0.9586
Akurasi pada data pengujian: 0.96


Kode ini mengukur kinerja model pada data uji setelah proses pelatihan selesai. Hasilnya adalah akurasi model pada data uji. Akurasi adalah rasio prediksi benar terhadap total predik

In [9]:
# Evaluasi akurasi data pelatihan
train_loss, train_acc = model.evaluate(train_images, train_labels)
print(f'Akurasi pada data pelatihan: {train_acc:.2f}')

1750/1750 [==============================] - 10s 6ms/step - loss: 0.1044 - accuracy: 0.9676
Akurasi pada data pelatihan: 0.97


Kode ini mengukur kinerja model pada data latih setelah proses pelatihan selesai. Hasilnya adalah akurasi model pada data latih. Akurasi adalah rasio prediksi benar terhadap total prediksi.

In [11]:
from sklearn.metrics import confusion_matrix

# Membuat prediksi pada data pengujian
predictions = model.predict(test_images)
predicted_labels = np.argmax(predictions, axis=1)

# Membuat matriks kebingungan
confusion = confusion_matrix(test_labels, predicted_labels)
print('Matriks Kebingungan:')
print(confusion)

438/438 [==============================] - 2s 5ms/step
Matriks Kebingungan:
[[1312    1    6    0    2    5    3    2    8    4]
 [   0 1566    8    5    3    0    1    3   11    3]
 [   8    7 1315    5    7    4    4   10   16    4]
 [   3    5   13 1332    1   21    2   12   30   14]
 [   1    0    3    2 1260    1    2    1    2   23]
 [   4    2    1   15    6 1195   15    0   28    7]
 [   7    3    2    0   10   10 1356    0    7    1]
 [   2    4    8    2    6    2    1 1452    1   25]
 [   7   10   10   11    6    2    4    6 1296    5]
 [   5    4    1    8   36    2    0   18   10 1336]]


Kode ini menghasilkan dan mencetak matriks kebingungan dari hasil prediksi model pada data uji.