# Praktikum 4
Klasifikasi dengan ANN

## Deskripsi
Pada praktikum kali ini, Anda diminta untuk membuat model ANN untuk mengklasifikasi potensi seorang customer akan meninggalkan perusahaan Anda atau tidak. Istirlah populer dari fenomena ini disebut sebagai 'churn'. Tingkat churn yang tinggi (chrun rate) akan berdampak tidak baik bagi perusahaan.

## Pra Pengolahan Data
### Langkah 1 - Import Library


In [1]:
# Mengimpor pustaka NumPy untuk operasi numerik
import numpy as np

# Mengimpor pustaka Pandas untuk manipulasi data dalam bentuk DataFrame
import pandas as pd

# Mengimpor pustaka TensorFlow untuk pemodelan dan pembelajaran mesin
import tensorflow as tf


### Langkah 2 - Load Data


In [2]:
# Mengimpor dataset dari file CSV 'Churn_Modelling.csv' menggunakan Pandas
dataset = pd.read_csv('Churn_Modelling.csv')

# Memisahkan data fitur (kolom 3 sampai sebelum kolom terakhir) ke dalam variabel 'X'
X = dataset.iloc[:, 3:-1].values

# Memisahkan data target (kolom terakhir) ke dalam variabel 'y'
y = dataset.iloc[:, -1].values


Cek data (X)

In [3]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


### Langkah 3 - Encoding Data Kategorikal


In [4]:
# Mengimpor LabelEncoder dari scikit-learn
from sklearn.preprocessing import LabelEncoder

# Membuat instansi LabelEncoder
le = LabelEncoder()

# Mengkodekan data dalam kolom ke-2 dari 'X' menjadi data numerik
X[:, 2] = le.fit_transform(X[:, 2])


Cek data (X) dengan print. Hasilnya,

In [5]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


### Langkah 4 - Encoding Kolom "Geography" dengan One Hot Encoder


In [6]:
# Mengimpor ColumnTransformer dan OneHotEncoder dari scikit-learn
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

# Membuat instansi ColumnTransformer untuk mengubah kolom ke-1 menjadi variabel dummy
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')

# Menggunakan ColumnTransformer untuk mengubah data 'X'
X = np.array(ct.fit_transform(X))


Cek data (X) dengan print. Hasilnya,

In [7]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


### Langkah 5 - Split Data


In [8]:
# Mengimpor train_test_split dari scikit-learn
from sklearn.model_selection import train_test_split

# Memisahkan data menjadi data pelatihan dan data pengujian (80% pelatihan, 20% pengujian)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)


### Langkah 6 - Scaling Fitur


In [9]:
# Mengimpor StandardScaler dari scikit-learn
from sklearn.preprocessing import StandardScaler

# Membuat instansi StandardScaler
sc = StandardScaler()

# Menskala data pelatihan
X_train = sc.fit_transform(X_train)

# Menskala data pengujian dengan parameter yang sama seperti data pelatihan
X_test = sc.transform(X_test)


## Membuat Model ANN


### Langkah 1 - Inisiasi Model ANN


In [10]:
# Membuat model berurutan (sequential) dengan TensorFlow
ann = tf.keras.models.Sequential()


### Langkah 2 - Membuat Input Layer dan Hidden Layer Pertama


In [11]:
# Menambahkan sebuah layer dense (terhubung penuh) ke dalam model jaringan saraf
# dengan 6 unit (neuron) dan fungsi aktivasi ReLU
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))


### Langkah 3 - Membuat Hidden Layer Kedua


In [12]:
# Menambahkan layer dense (terhubung penuh) tambahan ke dalam model jaringan saraf
# dengan 6 unit (neuron) dan fungsi aktivasi ReLU
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))


### Langkah 4 - Membuat Output Layer


In [13]:
# Menambahkan layer dense (terhubung penuh) tambahan ke dalam model jaringan saraf
# dengan 1 unit (neuron) dan fungsi aktivasi sigmoid
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))


## Training Model


### Langkah 1 - Compile Model (Menyatukan Arsitektur) ANN


In [14]:
# Mengompilasi model jaringan saraf dengan konfigurasi tertentu
# - 'adam': optimizer yang digunakan adalah Adam, yang merupakan algoritma optimisasi yang umum digunakan
# - 'binary_crossentropy': loss function yang digunakan untuk masalah klasifikasi biner
# - ['accuracy']: metrik yang akan dihitung adalah akurasi
ann.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])


### Langkah 2 - Fitting Model


In [15]:
# Melatih model jaringan saraf dengan data pelatihan
# - X_train: data fitur pelatihan
# - y_train: data target pelatihan
# - batch_size: ukuran batch yang digunakan selama pelatihan
# - epochs: jumlah iterasi pelatihan
ann.fit(X_train, y_train, batch_size=32, epochs=100)


Epoch 1/100
250/250 [==============================] - 1s 1ms/step - loss: 0.6433 - accuracy: 0.6814
Epoch 2/100
250/250 [==============================] - 0s 653us/step - loss: 0.5001 - accuracy: 0.7984
Epoch 3/100
250/250 [==============================] - 0s 660us/step - loss: 0.4497 - accuracy: 0.8066
Epoch 4/100
250/250 [==============================] - 0s 661us/step - loss: 0.4306 - accuracy: 0.8119
Epoch 5/100
250/250 [==============================] - 0s 654us/step - loss: 0.4151 - accuracy: 0.8234
Epoch 6/100
250/250 [==============================] - 0s 654us/step - loss: 0.3971 - accuracy: 0.8330
Epoch 7/100
250/250 [==============================] - 0s 623us/step - loss: 0.3840 - accuracy: 0.8375
Epoch 8/100
250/250 [==============================] - 0s 620us/step - loss: 0.3747 - accuracy: 0.8405
Epoch 9/100
250/250 [==============================] - 0s 619us/step - loss: 0.3689 - accuracy: 0.8426
Epoch 10/100
250/250 [==============================] - 0s 614us/step - los

## Membuat Prediksi


Diberikan informasi sebagai berikut,

- Geography: France
- Credit Score: 600
- Gender: Male
- Age: 40 years old
- Tenure: 3 years
- Balance: $ 60000
- Number of Products: 2
- Does this customer have a credit card ? Yes
- Is this customer an Active Member: Yes
- Estimated Salary: $ 50000

Apakah customer tersebut perlu dipertahankan?

### Modelkan Data Baru dan Buat Prediksi


In [16]:
# Menggunakan model 'ann' untuk memprediksi hasil berdasarkan data masukan
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

1/1 [==============================] - 0s 65ms/step
[[False]]


Apakah hasilnya False?

### Prediksi Dengan Data Testing


In [17]:
# Melakukan prediksi pada data pengujian menggunakan model 'ann'
y_pred = ann.predict(X_test)

# Mengubah prediksi menjadi nilai boolean (True/False) dengan threshold 0.5
y_pred = (y_pred > 0.5)

# Menggabungkan hasil prediksi (y_pred) dengan nilai aktual (y_test) dari data pengujian
# dan mencetak hasilnya
print(np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test), 1)), axis=1))


63/63 [==============================] - 0s 565us/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


### Cek Akurasi dan Confusion Matrix


In [18]:
# Mengimpor matriks konfusi (confusion matrix) dan metrik akurasi dari scikit-learn
from sklearn.metrics import confusion_matrix, accuracy_score

# Menghitung matriks konfusi
cm = confusion_matrix(y_test, y_pred)

# Mencetak matriks konfusi
print("Matriks Konfusi:")
print(cm)

# Menghitung dan mencetak akurasi model
accuracy = accuracy_score(y_test, y_pred)
print("Akurasi Model:", accuracy)


Matriks Konfusi:
[[1510   85]
 [ 190  215]]
Akurasi Model: 0.8625
