# Praktikum 4 - Klasifikasi dengan ANN

### Install Library Tensorflow

In [1]:
%pip install --upgrade pip

Note: you may need to restart the kernel to use updated packages.


In [2]:
%pip install tensorflow

Note: you may need to restart the kernel to use updated packages.


## Pra Pengolahan Data

#### Langkah 1 - Import Library

In [4]:
import numpy as np 
import pandas as pd
import tensorflow as tf

#### Langkah 2 - Load Data

In [5]:
dataset = pd.read_csv('dataset/Churn_Modelling.csv') # Import dataset
X = dataset.iloc[:, 3:-1].values # Mengambil kolom 3 sampai kolom terakhir
y = dataset.iloc[:, -1].values # Mengambil kolom terakhir

# Cek data (X)
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


#### Langkah 3 - Encoding Data Kategorikal

In [7]:
from sklearn.preprocessing import LabelEncoder # LabelEncoder = mengubah data kategorikal menjadi numerikal
le = LabelEncoder() # inisialisasi LabelEncoder
X[:, 2] = le.fit_transform(X[:, 2]) # mengubah data kategorikal menjadi numerikal

# Cek data (X)
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


#### Langkah 4 - Encoding Kolom "Geography" dengan One Hot Encoder

In [9]:
from sklearn.compose import ColumnTransformer # ColumnTransformer = mengubah data numerikal menjadi dummy variabel
from sklearn.preprocessing import OneHotEncoder # OneHotEncoder = mengubah data numerikal menjadi dummy variabel
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough') # inisialisasi ColumnTransformer
X = np.array(ct.fit_transform(X)) # mengubah data numerikal menjadi dummy variabel

# Cek data (X)
print(X)

[[1.0 0.0 1.0 ... 1 1 101348.88]
 [1.0 0.0 0.0 ... 0 1 112542.58]
 [1.0 0.0 1.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 1.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 1.0 ... 1 0 38190.78]]


#### Langkah 5 - Split Data

In [10]:
from sklearn.model_selection import train_test_split # train_test_split = membagi data menjadi data training dan data testing
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0) # inisialisasi train_test_split

#### Langkah 6 - Scaling Fitur

In [11]:
from sklearn.preprocessing import StandardScaler # StandardScaler = mengubah data menjadi data yang memiliki mean = 0 dan standard deviasi = 1
sc = StandardScaler() # inisialisasi StandardScaler
X_train = sc.fit_transform(X_train) # mengubah data menjadi data yang memiliki mean = 0 dan standard deviasi = 1
X_test = sc.transform(X_test) # mengubah data menjadi data yang memiliki mean = 0 dan standard deviasi = 1

## Membuat Model ANN

#### Langkah 1 - Inisiasi Model ANN

In [12]:
ann = tf.keras.models.Sequential() # inisialisasi model sequential

#### Langkah 2 - Membuat Input Layer dan Hidden Layer Pertama

In [13]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu')) # menambahkan layer input dan hidden layer pertama

#### Langkah 3 - Membuat Hidden Layer Kedua

In [14]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu')) # menambahkan layer input dan hidden layer kedua

#### Langkah 4 - Membuat Output Layer

In [15]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid')) # menambahkan layer output

## Training Model

#### Langkah 1 - Compile Model (Menyatukan Arsitektur) ANN

In [16]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy']) # mengcompile model

#### Langkah 2 - Fitting Model

In [17]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100) # training model

Epoch 1/100
250/250 [==============================] - 4s 5ms/step - loss: 0.5414 - accuracy: 0.7851
Epoch 2/100
250/250 [==============================] - 2s 6ms/step - loss: 0.4530 - accuracy: 0.7958
Epoch 3/100
250/250 [==============================] - 1s 5ms/step - loss: 0.4339 - accuracy: 0.7964
Epoch 4/100
250/250 [==============================] - 2s 8ms/step - loss: 0.4252 - accuracy: 0.7995
Epoch 5/100
250/250 [==============================] - 2s 8ms/step - loss: 0.4175 - accuracy: 0.8109
Epoch 6/100
250/250 [==============================] - 2s 9ms/step - loss: 0.4103 - accuracy: 0.8139
Epoch 7/100
250/250 [==============================] - 2s 7ms/step - loss: 0.4041 - accuracy: 0.8164
Epoch 8/100
250/250 [==============================] - 2s 8ms/step - loss: 0.3985 - accuracy: 0.8188
Epoch 9/100
250/250 [==============================] - 1s 6ms/step - loss: 0.3933 - accuracy: 0.8270
Epoch 10/100
250/250 [==============================] - 2s 6ms/step - loss: 0.3875 - accura

## Membuat Prediksi

Diberikan informasi sebagai berikut,

- Geography: France
- Credit Score: 600
- Gender: Male
- Age: 40 years old
- Tenure: 3 years
- Balance: $ 60000
- Number of Products: 2
- Does this customer have a credit card ? Yes
- Is this customer an Active Member: Yes
- Estimated Salary: $ 50000

Apakah customer tersebut perlu dipertahankan?

#### Modelkan Data Baru dan Buat Prediksi

In [27]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000, 0]])) > 0.5)

1/1 [==============================] - 0s 63ms/step
[[False]]


#### Prediksi Dengan Data Testing

In [28]:
y_pred = ann.predict(X_test) # prediksi data testing
y_pred = (y_pred > 0.5) # mengubah nilai probabilitas menjadi nilai biner
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1)) # menampilkan hasil prediksi dan nilai aktual

63/63 [==============================] - 0s 5ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


#### Cek Akurasi dan Confusion Matrix

In [29]:
from sklearn.metrics import confusion_matrix, accuracy_score # confusion_matrix = menampilkan confusion matrix, accuracy_score = menampilkan akurasi
cm = confusion_matrix(y_test, y_pred) # inisialisasi confusion matrix
print(cm) # menampilkan confusion matrix
accuracy_score(y_test, y_pred) # menampilkan akurasi

[[1514   81]
 [ 199  206]]


0.86