# Tugas

- Lakukan klasifikasi pada data MNIST dengan menggunakan model ANN
- Anda diperbolehkan melakukan eksplorasi terhadap,
    - Metode pra pengolahan
    - Pemilihan fitur
    - Arsitektur ANN
    - Fungsi Aktiviasi
- ANN diimplementasikan dengan menggunakan ```tensorflow```.
- **DIKERJAKAN SECARA BERKELOMPOK**
- **JELASKAN HASIL YANG ANDA DAPATKAN,**
    - **AKURASI**
    - **CONFUSION MATRIX**
    - **KONFIGURASI MODEL --> MULAI DARI PRA PENGOLAHAN SAMPAI ARSITEKTUR ANN**

In [4]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

In [3]:
# Load the MNIST dataset
mnist = keras.datasets.mnist # 28x28 images of hand-written digits 0-9
(train_images, train_labels), (test_images, test_labels) = mnist.load_data() # Split into training and test sets

# Preprocessing
train_images, test_images = train_images / 255.0, test_images / 255.0 # Scale the pixel values from 0 to 1

# Build the ANN model
model = keras.Sequential([
    layers.Flatten(input_shape=(28, 28)),  # Flatten the 28x28 input images
    layers.Dense(128, activation='relu'),  # Hidden layer with ReLU activation
    layers.Dropout(0.2),                  # Dropout layer to reduce overfitting
    layers.Dense(10, activation='softmax') # Output layer with 10 classes and softmax activation
])

# Compile the model
model.compile(optimizer='adam', # Optimizer
              loss='sparse_categorical_crossentropy', # Loss function
              metrics=['accuracy']) # Accuracy metric

# Train the model
model.fit(train_images, train_labels, epochs=5) # Train the model for 5 epochs

# Evaluate the model on the test data
test_loss, test_accuracy = model.evaluate(test_images, test_labels) # Evaluate the model on the test data using `evaluate`

print(f'Test accuracy: {test_accuracy}') # Print test accuracy

# Confusion Matrix
predictions = model.predict(test_images) # Make predictions on the test data
confusion_matrix = tf.math.confusion_matrix(test_labels, tf.argmax(predictions, axis=1)) # Create a confusion matrix on the test data
print('Confusion Matrix:') # Print the confusion matrix
print(confusion_matrix) # Print the confusion matrix


Epoch 1/5
1875/1875 [==============================] - 26s 12ms/step - loss: 0.2956 - accuracy: 0.9142
Epoch 2/5
1875/1875 [==============================] - 18s 9ms/step - loss: 0.1443 - accuracy: 0.9571
Epoch 3/5
1875/1875 [==============================] - 16s 9ms/step - loss: 0.1065 - accuracy: 0.9680
Epoch 4/5
1875/1875 [==============================] - 17s 9ms/step - loss: 0.0863 - accuracy: 0.9734
Epoch 5/5
313/313 [==============================] - 3s 7ms/step - loss: 0.0762 - accuracy: 0.9768
Test accuracy: 0.9768000245094299
313/313 [==============================] - 2s 6ms/step
Confusion Matrix:
tf.Tensor(
[[ 971    0    0    1    1    1    2    1    1    2]
 [   0 1127    3    0    0    1    2    0    2    0]
 [   8    3 1001    1    2    0    4    7    6    0]
 [   2    1    8  984    0    6    0    4    4    1]
 [   0    0    2    0  959    0    8    1    3    9]
 [   3    2    0    5    0  872    5    1    2    2]
 [   5    3    0    1    2    2  945    0    0    0]
 [ 