# Praktikum 4
Klasifikasi dengan ANN

## Langkah 1 - Import Library

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

## Langkah 2 - Load Data

In [ ]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

Cek data (X)

In [4]:
print(X)


[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


## Langkah 3 - Encoding Data Kategorikal

In [5]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])


Cek data (X) dengan print. Hasilnya,

In [6]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


## Langkah 4 - Encoding Kolom "Geography" dengan One Hot Encoder

In [7]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

Cek data (X) dengan print. Hasilnya,

In [8]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


## Langkah 5 - Split Data

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

## Langkah 6 - Scaling Fitur

In [10]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Membuat Model ANN

## Langkah 1 - Inisiasi Model ANN

In [11]:
ann = tf.keras.models.Sequential()

## Langkah 2 - Membuat Input Layer dan Hidden Layer Pertama

In [12]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

## Langkah 3 - Membuat Hidden Layer Kedua

In [13]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

## Langkah 4 - Membuat Output Layer

In [14]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

## Training Model

## Langkah 1 - Compile Model (Menyatukan Arsitektur) ANN

In [15]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

## Langkah 2 - Fitting Model

In [16]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 1s 969us/step - loss: 0.7370 - accuracy: 0.5200
Epoch 2/100
250/250 [==============================] - 0s 973us/step - loss: 0.5315 - accuracy: 0.7939
Epoch 3/100
250/250 [==============================] - 0s 963us/step - loss: 0.4765 - accuracy: 0.7981
Epoch 4/100
250/250 [==============================] - 0s 952us/step - loss: 0.4458 - accuracy: 0.8046
Epoch 5/100
250/250 [==============================] - 0s 953us/step - loss: 0.4245 - accuracy: 0.8135
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4093 - accuracy: 0.8173
Epoch 7/100
250/250 [==============================] - 0s 966us/step - loss: 0.3979 - accuracy: 0.8192
Epoch 8/100
250/250 [==============================] - 0s 959us/step - loss: 0.3888 - accuracy: 0.8205
Epoch 9/100
250/250 [==============================] - 0s 953us/step - loss: 0.3826 - accuracy: 0.8264
Epoch 10/100
250/250 [==============================] - 0s 944us/step - los

Membuat Prediksi

Diberikan informasi sebagai berikut,
* Geography: France
* Credit Score: 600
* Gender: Male
* Age: 40 years old
* Tenure: 3 years
* Balance: 60000
* Number of Products: 2
* Does this customer have a credit card ? Yes
* Is this customer an Active Member: Yes
* Estimated Salary: $ 50000

Apakah customer tersebut perlu dipertahankan?

Modelkan Data Baru dan Buat Prediksi

In [17]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

1/1 [==============================] - 0s 96ms/step
[[False]]


Apakah hasilnya False?
- Ya, Hasil yang di dapatkan adalah false dan hal ini menunjukkan bahwa prediksi yang diberikan oleh model memiliki nilai kurang dari atau sama dengan 0,5.

Prediksi Dengan Data Testing

In [18]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

 1/63 [..............................] - ETA: 1s

63/63 [==============================] - 0s 1ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


Cek Akurasi dan Confusion Matrix

In [19]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1508   87]
 [ 186  219]]


0.8635