In [19]:
import numpy as np # untuk bekerja dengan array multidimensi dan fungsi matematika ayang efisien
import pandas as pd # menyediakan struktur data dan alat analisis data yang mudah digunakan
import tensorflow as tf # untuk membangun model dan melatih model dalam konteks tiruan

In [20]:
dataset = pd.read_csv('Churn_Modelling.csv') # membaca file CSV 
X = dataset.iloc[:, 3:-1].values # mengestrak set fitur
y = dataset.iloc[:, -1].values # mengestrak set label

print(X) # mencetak hasil

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [21]:
from sklearn.preprocessing import LabelEncoder # melakukan label encoding pada kolom
le = LabelEncoder() # membuat objek 
X[:, 2] = le.fit_transform(X[:, 2]) # mengubah nilai kategori pada kolom ketiga

print(X) # mencetak hasil

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [22]:
from sklearn.compose import ColumnTransformer  # untuk melakukan transformasi pada subset tertentu dari kolom
from sklearn.preprocessing import OneHotEncoder # untuk melakukan one hot encoding pada variabel kategorikal

# membuat objek yang akan mentrasformasikan kolom di dalam dataset
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X)) # melakukan tranformasi pada data 'X'

print(X) # mencetak hasil tranformasi

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [23]:
from sklearn.model_selection import train_test_split # import modul untuk membagi dataset 

# membagi dataset menjadi subset pelatihan dan pengujian dengan ukuran sebesar 20% dari dataset dan pembagian dilakukan secara acak 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [24]:
from sklearn.preprocessing import StandardScaler # untuk penskalaan fitur pada dataset
sc = StandardScaler() # untuk penskalaan fitur pada dataset
X_train = sc.fit_transform(X_train) # untuk mempelajari dan menerapkan penskalaan pada subset pelatihan
X_test = sc.transform(X_test) # untuk menerapkan penskalaan yang telah dipelajari dari subset pelatihan ke subset pengujian

In [25]:
# membuat objek model neural network 
ann = tf.keras.models.Sequential()

In [26]:
# menambahkan lapisam dense 
ann.add(tf.keras.layers.Dense(units=6, activation='relu')) # relu = Rectified Linear Unit

In [27]:

ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [28]:
# menambahkan lapisam dense  
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid')) # untuk masalah fungsi aktivasi sigmoid

In [29]:
# mengompilasi model sequential 
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [30]:
# melatih model Sequential yang telah dikompilasi sebelumnya menggunakan data pelatihan
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 2s 3ms/step - loss: 0.5511 - accuracy: 0.7651
Epoch 2/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4742 - accuracy: 0.7968
Epoch 3/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4459 - accuracy: 0.8033
Epoch 4/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4279 - accuracy: 0.8061
Epoch 5/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4164 - accuracy: 0.8092
Epoch 6/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4048 - accuracy: 0.8145
Epoch 7/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3921 - accuracy: 0.8254
Epoch 8/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3805 - accuracy: 0.8332
Epoch 9/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3720 - accuracy: 0.8400
Epoch 10/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3652 - accura

In [31]:
# melakukan prediksi menggunakan model Sequential yang telah dilatih sebelumnya pada data baru
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

1/1 [==============================] - 0s 158ms/step
[[False]]


In [32]:
# melakukan prediksi menggunakan model Sequential yang telah dilatih sebelumnya pada data pengujian (X_test)
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

63/63 [==============================] - 0s 2ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [33]:
from sklearn.metrics import confusion_matrix, accuracy_score # untuk menghitung matriks kebingungan dan akurasi dari hasil prediksi
cm = confusion_matrix(y_test, y_pred) # menghitung antara nilai target dan nilai prediksi dan di simpan dalam cm
print(cm) # mencetak hasil cm
accuracy_score(y_test, y_pred) # menghitung akurasi dari hasil prediksi 

[[1516   79]
 [ 201  204]]


0.86